/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.joyeríainventario.views;

import com.joyeríainventario.dao.JoyaDAO;
import com.joyeríainventario.models.Joya;
import com.joyeríainventario.vos.JoyaVO;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author esteb
 */
public class FrmFormularioJoyas extends javax.swing.JFrame {

    /**
     * Creates new form FrmAgregarJoya
     */
    private JoyaDAO eboTabla = new JoyaDAO();
    private Joya joyaSeleccionada;

    private void seleccionarJoya(Joya joya) {
        joyaSeleccionada = joya;
        TxtNombre.setText(joya.getNombre());
        TxtMaterial.setText(joya.getMaterial());
        TxtPeso.setText(String.valueOf(joya.getPeso()));
        TxtPrecio.setText(String.valueOf(joya.getPrecio()));
        SpStock.setValue(joya.getStock());
    }

    // limpiamos los campos
    private void limpiarCampos() {
        TxtNombre.setText("");
        TxtMaterial.setText("");
        TxtPeso.setText("");
        TxtPrecio.setText("");
        SpStock.setValue(0);
        joyaSeleccionada = null;
    }

    public FrmFormularioJoyas() throws IOException, Exception {
        initComponents();
        listarJoya();
        limpiarCampos();

        setTitle("Formulario Joyas - Creacion de inventario de Joyas");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    public void listarJoya() throws IOException, Exception {
        eboTabla.listarJoya(tbTablaJoya);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtMaterial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtPeso = new javax.swing.JTextField();
        TxtPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTablaJoya = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        SpStock = new javax.swing.JSpinner();
        BtnBuscar = new javax.swing.JButton();
        TxtBuscarJoya = new javax.swing.JTextField();
        btnAgregarJoya = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Nombre de la Joya: ");

        jLabel1.setText("Material: ");

        jLabel3.setText("Peso:");

        jLabel4.setText("Precio:");

        tbTablaJoya.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTablaJoya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTablaJoyaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTablaJoya);

        jLabel5.setText("Stock:");

        BtnBuscar.setBackground(new java.awt.Color(0, 204, 204));
        BtnBuscar.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        BtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscar.setText("Buscar Joya");
        BtnBuscar.setBorder(null);
        BtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBuscarMouseClicked(evt);
            }
        });
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        btnAgregarJoya.setBackground(new java.awt.Color(0, 153, 51));
        btnAgregarJoya.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarJoya.setText("Agregar Joya");
        btnAgregarJoya.setBorder(null);
        btnAgregarJoya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJoyaActionPerformed(evt);
            }
        });

        btnVolver.setForeground(new java.awt.Color(0, 51, 204));
        btnVolver.setText("< Volver");
        btnVolver.setBorder(null);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(204, 0, 51));
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(null);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 51, 255));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar Stock");
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TxtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnAgregarJoya, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(TxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SpStock, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtBuscarJoya, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarJoya, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBuscarJoya, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jMenu1.setText("Inventario");

        jMenuItem1.setText("Agregar Joyas");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventas");

        jMenuItem2.setText("Realizar Compra");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTablaJoyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTablaJoyaMouseClicked
        // Evento para visualizar la tabla
        int select = tbTablaJoya.rowAtPoint(evt.getPoint());
        TxtNombre.setText(tbTablaJoya.getValueAt(select, 0) + "");
        TxtMaterial.setText(tbTablaJoya.getValueAt(select, 1) + "");
        TxtPeso.setText(tbTablaJoya.getValueAt(select, 2) + "");
        TxtPrecio.setText(tbTablaJoya.getValueAt(select, 3) + "");
        SpStock.setValue(tbTablaJoya.getValueAt(select, 4) + "");
    }//GEN-LAST:event_tbTablaJoyaMouseClicked

    private void btnAgregarJoyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJoyaActionPerformed
        // agregamos una joya al inventario
        if (TxtNombre.getText().isEmpty() || TxtMaterial.getText().isEmpty()
                || TxtPeso.getText().isEmpty() || TxtPrecio.getText().isEmpty()
                || SpStock.getValue() == null) {
            JOptionPane.showMessageDialog(null, "Se necesita llenar todos los campos, por favor ingrese los datos");
        } else {
            Joya joya = new Joya();
            joya.setNombre(TxtNombre.getText());
            joya.setMaterial(TxtMaterial.getText());
            joya.setPeso(Double.parseDouble(TxtPeso.getText()));
            joya.setPrecio(Double.parseDouble(TxtPrecio.getText()));
            joya.setStock((Integer) SpStock.getValue());

            JoyaDAO agregar = new JoyaDAO();

            try {
                agregar.agregarJoya(joya);
                limpiarCampos();
                listarJoya();
            } catch (Exception ex) {
                Logger.getLogger(FrmFormularioJoyas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAgregarJoyaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void BtnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuscarMouseClicked

    }//GEN-LAST:event_BtnBuscarMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // Obtenemos la joya seleccionada
        String materialBusqueda = TxtMaterial.getText().trim();

        // verificamos si se ha seleccionado una fila
        if (materialBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el material de la joya para eliminar");
            return;
        }

        try {
            // buscamos la joya por el material
            Joya joya = eboTabla.buscarPorMaterial(materialBusqueda);

            // verificamos si se encontro la joya
            if (joya == null) {
                JOptionPane.showMessageDialog(null, "No se encontró ninguna joya con el material: " + materialBusqueda);
                return;
            }

            // confirmación de eliminación
            int confirmacion = JOptionPane.showConfirmDialog(null,
                    "¿Estás seguro que desea eliminar esta Joya?",
                    "Confirmar Eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                try {
                    // eliminamos la joya 
                    eboTabla.eliminarJoya(joya.getIdJoya());

                    // actualizamos la tabla
                    listarJoya();
                    JOptionPane.showMessageDialog(null, "Joya eliminada exitosamente");

                    // limpiamos los campos del formulario
                    limpiarCampos();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null,
                            "Error al eliminar una joya: " + ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Error al eliminar una joya: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        /// buscamos una joya por el id para actualizarlo
        String materialBusqueda = TxtBuscarJoya.getText().trim();

        if (materialBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un material para buscar");
            return;
        }

        try {
            // buscamos por el material ingreado
            Joya joya = eboTabla.buscarPorMaterial(materialBusqueda);

            // verificamos si se encontro la joya
            if (joya != null) {
                TxtNombre.setText(joya.getNombre());
                TxtMaterial.setText(joya.getMaterial());
                TxtPeso.setText(String.valueOf(joya.getPeso()));
                TxtPrecio.setText(String.valueOf(joya.getPrecio()));
                SpStock.setValue(joya.getStock());

                JOptionPane.showMessageDialog(null, "Joya encontrado");
                TxtBuscarJoya.setText("");
            } else {
                JOptionPane.showMessageDialog(null,
                        "No se encontró ninguna joya con el material: " + materialBusqueda,
                        "Busqueda sin resultados",
                        JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "Error al buscar joya: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Limpiamos los datos del formulario
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            // pedimos el ID de la joya
            String idInput = JOptionPane.showInputDialog(null, "Ingrese el ID de la joya a actualizar:", "Actualizar Stock", JOptionPane.QUESTION_MESSAGE);

            if (idInput == null || idInput.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un ID valido");
                return;
            }

            // convertimos el ID ingresado a entero
            int idJoya;
            try {
                idJoya = Integer.parseInt(idInput);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El ID debe ser un número entero.");
                return;
            }

            // Optenemos la joya seleccionada usando el ID
            Joya joya = eboTabla.buscarJoyaPorId(idJoya);

            if (joya == null) {
                JOptionPane.showMessageDialog(null, "No se encontró una Joya con ese ID.");
                return;
            }

            // Pedimos el nuevo valor del stock
            String nuevaStockInput = JOptionPane.showInputDialog(null, "Ingrese el nuevo stock:", "Actualizar Stock", JOptionPane.QUESTION_MESSAGE);

            if (nuevaStockInput == null || nuevaStockInput.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe ingresar un stock válido.");
                return;
            }

            // Convertimos el stock ingresado a entero
            int nuevoStock;
            try {
                nuevoStock = Integer.parseInt(nuevaStockInput);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "El stock debe ser un número entero.");
                return;
            }

            // Confirmamos la actualización
            int confirmacion = JOptionPane.showConfirmDialog(null,
                    "¿Estás seguro de desea actualizar el stock de esta Joya?",
                    "Confirmar actualización",
                    JOptionPane.YES_NO_OPTION);

            // Procedemos si el usuario confirma
            if (confirmacion == JOptionPane.YES_OPTION) {
                // Actualizamos el stock
                joya.setStock(nuevoStock);
                eboTabla.modificarJoya(joya);

                // Mensaje de éxito
                JOptionPane.showMessageDialog(null, "Stock de la Joya actualizado exitosamente");

                // Actualizamos la tabla
                listarJoya();

                // Limpiamos los campos
                limpiarCampos();
            }
        } catch (Exception e) {
            Logger.getLogger(FrmFormularioJoyas.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, "Error al actualizar el stock: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioJoyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioJoyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioJoyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFormularioJoyas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmFormularioJoyas().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FrmFormularioJoyas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JSpinner SpStock;
    private javax.swing.JTextField TxtBuscarJoya;
    private javax.swing.JTextField TxtMaterial;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPeso;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarJoya;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTablaJoya;
    // End of variables declaration//GEN-END:variables
}
